[package]
name = "rust_example"
version = "0.1.0"
authors = ["Zsolt Kr√ºpl <hg2ecz@ham.hu>"]

[lib]
name = "rust_example"
crate-type = ["dylib"]


[dependencies.cpython]
version = "0.2.*"

# Python3
features = ["extension-module"]

# Python2
#default-features = false
#features = ["python27-sys"]
